#!/usr/bin/env python3
"""Read the *_3rdparty CBCT series from the read-only USB mirror, de-identify,
and write one gzipped NRRD per volume plus a provenance sidecar.

The working copy never contains PHI: NRRD carries only the fields written here,
and none of them are identifiers. That is why no de-identified DICOM intermediate
is produced -- it would cost ~780 MB to hold data we would only convert again.
Originals in the mirror are never modified.

Values are written as int16 Hounsfield-like units. The _3rdparty export stores
16 bits with RescaleSlope 0.0625, so this rounds away sub-HU precision -- which
is ~2 orders of magnitude below this scanner's noise floor and below any
threshold decision in docs/cbct-survey.md. It is still the right source: the
12-bit exports floor rather than round, carrying a -0.5 HU bias.

Usage:  python3 tools/cbct/prepare.py <mirror-dir> <out-dir>
"""
import gzip, hashlib, json, os, sys, datetime
import numpy as np
import pydicom

VOLUMES = ("centered", "mandibular", "maxillary")

# Tags carrying identifiers, per docs/cbct-survey.md. Dropped, never copied.
IDENTIFIERS = [
    (0x0010,0x0010), (0x0010,0x0020), (0x0010,0x0030), (0x0010,0x0040),
    (0x0008,0x0080), (0x0008,0x0081), (0x0008,0x0090), (0x0008,0x1010),
    (0x0008,0x1030), (0x0020,0x0010), (0x0018,0x1020), (0x0008,0x0050),
]


def find_series(mirror, name):
    """Locate the CT slice files of <name>_3rdparty, ordered by InstanceNumber."""
    root = os.path.join(mirror, f"{name}_3rdparty")
    if not os.path.isdir(root):
        raise SystemExit(f"missing export folder: {root}")
    files = []
    for dirpath, _, filenames in os.walk(root):
        for fn in filenames:
            if fn == "DICOMDIR":
                continue
            files.append(os.path.join(dirpath, fn))
    slices = []
    for p in files:
        try:
            ds = pydicom.dcmread(p, stop_before_pixels=True)
        except Exception:
            continue
        if getattr(ds, "Modality", None) != "CT":
            continue
        if "ORIGINAL" not in list(getattr(ds, "ImageType", [])):
            continue
        slices.append((int(ds.InstanceNumber), p, ds))
    if not slices:
        raise SystemExit(f"no ORIGINAL CT slices under {root}")
    slices.sort()
    return slices


def check_geometry(slices):
    """Fail loudly on anything that would silently distort later measurements."""
    _, _, ds0 = slices[0]
    zs = []
    for _, p, ds in slices:
        if (ds.Rows, ds.Columns) != (ds0.Rows, ds0.Columns):
            raise SystemExit("inconsistent matrix size across slices")
        if list(ds.ImageOrientationPatient) != list(ds0.ImageOrientationPatient):
            raise SystemExit("inconsistent ImageOrientationPatient across slices")
        if list(ds.PixelSpacing) != list(ds0.PixelSpacing):
            raise SystemExit("inconsistent PixelSpacing across slices")
        zs.append(float(ds.ImagePositionPatient[2]))
    zs = np.array(zs)
    dz = np.diff(zs)
    if dz.size and (dz.max() - dz.min()) > 1e-4:
        raise SystemExit(f"irregular slice spacing: {dz.min()} .. {dz.max()}")
    # dz comes from differencing large coordinates, so it carries float noise
    # (0.1599999999999966). Round it: the spacing is uniform to within 1e-4 by
    # the check above, and a ragged figure in the header propagates forever.
    dz = np.round(dz, 9)
    iop = [float(v) for v in ds0.ImageOrientationPatient]
    if iop != [1, 0, 0, 0, 1, 0]:
        raise SystemExit(f"unexpected ImageOrientationPatient {iop}; "
                         "the LPS reasoning in docs/cbct-survey.md assumes axial")
    return float(dz[0]) if dz.size else round(float(ds0.SliceThickness), 9)


def read_volume(slices):
    """Stack into (z, y, x) int16 Hounsfield-like units."""
    _, _, ds0 = slices[0]
    ny, nx = int(ds0.Rows), int(ds0.Columns)
    vol = np.empty((len(slices), ny, nx), dtype=np.int16)
    for i, (_, p, _) in enumerate(slices):
        ds = pydicom.dcmread(p)
        slope = float(getattr(ds, "RescaleSlope", 1))
        inter = float(getattr(ds, "RescaleIntercept", 0))
        hu = ds.pixel_array.astype(np.float32) * slope + inter
        vol[i] = np.rint(hu).astype(np.int16)
    return vol


def write_nrrd(path, vol, origin, spacing):
    """Minimal gzip-encoded NRRD. Axis order on disk is x fastest, matching
    'space directions' below; vol arrives as (z, y, x) so it already matches."""
    hdr = [
        "NRRD0004",
        "# Generated by tools/cbct/prepare.py -- de-identified, no PHI.",
        "type: short",
        "dimension: 3",
        "space: left-posterior-superior",
        f"sizes: {vol.shape[2]} {vol.shape[1]} {vol.shape[0]}",
        f"space directions: ({spacing[0]},0,0) (0,{spacing[1]},0) (0,0,{spacing[2]})",
        "kinds: domain domain domain",
        "endian: little",
        "encoding: gzip",
        f"space origin: ({origin[0]},{origin[1]},{origin[2]})",
        "",
    ]
    with open(path, "wb") as f:
        f.write(("\n".join(hdr) + "\n").encode("ascii"))
        f.write(gzip.compress(vol.astype("<i2").tobytes(), 6))


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    mirror, outdir = sys.argv[1], sys.argv[2]
    os.makedirs(outdir, exist_ok=True)
    manifest = {
        "generated": datetime.datetime.now().isoformat(timespec="seconds"),
        "source": "Sirona XG3D CBCT, *_3rdparty export (16-bit, uncompressed)",
        "units": "int16, Hounsfield-like; NOT calibrated HU (see docs/cbct-survey.md)",
        "deidentified": True,
        "identifier_tags_dropped": [f"{g:04X},{e:04X}" for g, e in IDENTIFIERS],
        "volumes": {},
    }
    for name in VOLUMES:
        print(f"[{name}] locating series ...", flush=True)
        slices = find_series(mirror, name)
        dz = check_geometry(slices)
        _, _, ds0 = slices[0]
        origin = [float(v) for v in ds0.ImagePositionPatient]
        spacing = [float(ds0.PixelSpacing[1]), float(ds0.PixelSpacing[0]), dz]
        print(f"[{name}] {len(slices)} slices, {spacing} mm, reading ...", flush=True)
        vol = read_volume(slices)
        out = os.path.join(outdir, f"{name}.nrrd")
        write_nrrd(out, vol, origin, spacing)
        digest = hashlib.sha256(open(out, "rb").read()).hexdigest()
        manifest["volumes"][name] = {
            "file": os.path.basename(out),
            "sha256": digest,
            "shape_zyx": list(vol.shape),
            "spacing_xyz_mm": spacing,
            "origin_lps": origin,
            "value_range": [int(vol.min()), int(vol.max())],
            "series_date": str(getattr(ds0, "SeriesDate", "")),
            "series_time": str(getattr(ds0, "SeriesTime", "")),
            "kvp": float(getattr(ds0, "KVP", 0)) or None,
            "size_bytes": os.path.getsize(out),
        }
        print(f"[{name}] wrote {out} "
              f"({os.path.getsize(out)/1e6:.0f} MB, range {vol.min()}..{vol.max()})",
              flush=True)
    with open(os.path.join(outdir, "volumes.json"), "w") as f:
        json.dump(manifest, f, indent=2)
    print("wrote", os.path.join(outdir, "volumes.json"))


if __name__ == "__main__":
    main()
